### ISSUE TITLE
Undefined array key "ItemDescriptionLanguages" in C:\xampp\htdocs\weberp\Stocks.php

### ISSUE THREAD

**Issue by dalers** [timschofield/webERP#777]
Stumbled across this today. Not a high priority but wanted to flag for when there's nothing else to do.....  ;-)

```
Warning: Undefined array key "ItemDescriptionLanguages" in C:\xampp\htdocs\weberp\Stocks.php on line 26
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in C:\xampp\htdocs\weberp\Stocks.php on line 26
```

To replicate access menu [Inventory > Maintenance > Add a new item]

config.php:

```
error_reporting(-1);
$Debug = 2;
```

<img width="1479" height="1225" alt="Image" src="https://github.com/user-attachments/assets/1f266670-a86d-40b0-bf51-a5bdc0676f1c" />

**Comment by timschofield** [comment]
Hi Dale, I think if you go into Setup->System Parameters and save it, you should find this goes away.

Tim

**Comment by dalers** [comment]
Hi Tim, thanks for suggestion but it doesn't seem to have any effect.

I accessed [Setup > General > System Parameters] which reported warning: 

`Warning: Undefined array key "ItemDescriptionLanguages" in C:\xampp\htdocs\weberp\SystemParameters.php on line 588`

<img width="1233" height="737" alt="Image" src="https://github.com/user-attachments/assets/d8a60eb8-7ea7-439c-b3cc-54b3c8a400fc" />

I clicked [Update] (leaving languages set to None) which reported the same warning.

```
SUCCESS Report : System configuration updated
 System Parameters
 Warning: Undefined array key "ItemDescriptionLanguages" in C:\xampp\htdocs\weberp\SystemParameters.php on line 364
```

<img width="1479" height="664" alt="Image" src="https://github.com/user-attachments/assets/b6feb2c6-53a4-4bbb-9d18-56357f3af625" />

Accessing [Inventory > Maintenance > Add a new item] still results in the warning reported originally.

I then selected ""English United States" for "Languages to Maintain Translations for Item Descriptions" in the system parameters (thinking a variable may need initializing same as your line of thinking iiuc) but "Update" didn't seem to have any effect (the language did not seem to get saved, presumably because of the error). 

Now for the really confusing part. I found the warning only occurs on a new database I created within the last couple months (using the installer) but not with an older database created perhaps 9 months ago. That _seems_ to me to imply the installer at the time the database was created missed some configuration that can't be resolved later by the user (e.g. by updating the System Parameters). Does that make sense?

I'll see if I can recreate the issue with a new db created using the installer, but I'm not sure when I will be able to dedicate the time.

**Comment by timschofield** [comment]
I think this is fixed now Dale.

Tim

**Comment by dalers** [comment]
Hi guys, just found the cause of my original issue and I don't believe commit https://github.com/pakricard/Standard-webERP/commit/7d711054a4f72ad2b4663487364a8b388884c6a3 (referenced by @pakricard) is related.

A new database I created some weeks/months ago using the installer was missing the "ItemDescriptionLanguages" config variable while it was included in my production database which was created much earlier. I'm guessing that at some point in time, "ItemDescriptionLanguages" was missed by the installer but was included in an update.php.

**Comment by timschofield** [comment]
There was a problem when the ItemDescriptionLanguages config variable is unset. The commit https://github.com/timschofield/webERP/commit/4a740a63e5326cc1145d37818fcc2681e500d970 fixes this.

Tim

**Comment by dalers** [comment]
I was still seeing the undefined error even after updating and had to manually add ItemDescriptionLanguages to the config table to prevent the error.

**Comment by dalers** [comment]
The "Warning: Undefined array key "ItemDescriptionLanguages" was reported again in a new db created by the installer when attempting to configure System Parameters (Setup > General > System Parameters).

<img width="1566" height="1114" alt="Image" src="https://github.com/user-attachments/assets/ab71ac62-65e1-4c9d-8e4d-fdd8c20beafa" />

It would seem the installer misses the ItemDescriptionLanguages config variable. I manually added the config value to resolve the issue (i.e. no warning).

```
INSERT INTO `config` (`confname`, `confvalue`) VALUES
('ItemDescriptionLanguages', ',');
```
